---
title: "State Funding System Analysis"
format: html
editor: visual
---

## Base Funding

-   If your state has a base funding amount, would you characterize it as adequate, inadequate, or too generous? How does it factor into funding policy conversations? Is it a "known" figure that features in debate/discussion, or is it more of a "hidden" element?



## Funding for Student Needs

-   Are there any student or district categories in which your state does not have weights or funding streams for what you wish you did? Would you characterize funding allocated for low-income students, English learners, and/or students with disabilities as adequate and equitably distributed? Why or why not?



## The Role of Local Funds

-   How do you think about the role of local funds in your systems? What's your ideal? What practical or political challenges do you anticipate around potentially changing the role of local funds?



## Funding Choice Programs

-   Is funding for schools of choice a major concern for your state or your organization? How would you like to see schools of choice funded differently, if at all?


